### ISSUE TITLE
Kombination von Filterfelder und Zeitraum kann zu leerer Ergebnisliste führen

### ISSUE THREAD

**Issue by stefan-schiffer** [FlorianKiesl/FinzLinz#11]
Diese Veranstaltung finde ich nicht, egal welchen Zeitraum ich einstelle:

![image](https://user-images.githubusercontent.com/4481320/53330608-3b047d80-38ef-11e9-93ad-a1a3479a4ad0.png)

**Comment by FlorianKiesl** [comment]
Mhm es scheint so als wäre hier kein Organisierer eingetragen und deshalb wird es nicht angezeigt.
@Luker666 Datensäuberung am Server oder soll ich das am Client berücksichtigen?

**Comment by stefan-schiffer** [comment]
Ich habe keine Veranstaltung gefunden, die nur an einem bestimmten Tag stattfindet und nicht während eines längeren Zeitraums. Bitte um ein Beispiel.

**Comment by FlorianKiesl** [comment]
Bienen & Garten: Bienenfreundlich Gärtnern findet z.B. heute statt
