### ISSUE TITLE
Auswahl eines Eintrags eines Filterfelds soll die anderen Einträge aktualisieren

### ISSUE THREAD

**Issue by stefan-schiffer** [FlorianKiesl/FinzLinz#3]
Wenn ein Eintrag in einem Filterfeld ausgewählt wird, soll FinzLinz die Einträge der anderen Filterfelder automatisch so aktualisieren, dass es nur noch dazu passenden Einträge anzeigt. **Das gilt auch für das Feld "Zeitraum"**, weil es sonst passieren kann, dass man eine Veranstaltung auswählt, aber kein Ergebnis bekommt.

Derzeit zeigt FinzLinz  unabhängig von der Auswahl in einem Filterfeld immer alle Einträge in den anderen Feldern, was dazu führt, dass Einträge, die nicht zueinander passen, zu einer leeren Ergebnisliste führen.

**Falsch:**
![image](https://user-images.githubusercontent.com/4481320/53328776-fd9df100-38ea-11e9-98b1-cd0ce6d02669.png)

**Comment by FlorianKiesl** [comment]
Ja ich verstehe, ich muss mir das noch überlegen ob es nicht zu zirkulären Bezügen führen könnte und dies zu Problemen führt.

**Comment by stefan-schiffer** [comment]
Warum zirkuläre Bezüge? Sobald ein Eintrag ausgewählt wird, werden die anderen Einträge so gefiltert, dass sie dazu passen. Was wären solche zirkulären Bezüge?

**Comment by FlorianKiesl** [comment]
Ich meine wenn alle Felder untereinander abhängigkeiten haben, ist das für mich ein Zirkelbezug. Aber wie gesagt ich überlegs mir und bau es einmal ein, vielleicht denk ich nur zu kompliziert.

**Comment by FlorianKiesl** [comment]
implemented
